### ISSUE TITLE
Add support for Portal items shared groups information

### ISSUE THREAD

**Issue by medspx** [Esri/arcgis-python-api#182] opened 2018-02-21 12:27 UTC
Hello,

it seems that the ArcGIS Python API is lacking a way to retrieve fine details about the shared groups of one Portal item. I can find some information in the .access property (with org/private or public levels) but nothing about the groups in which the item is shared.

In the REST API, you have to use [the User content](https://developers.arcgis.com/rest/users-groups-and-items/user-content.htm) to make a request against an item id to grab a sharing object which have a groups property.

It seems that there is nothing in the Python API to do this. As a workaround, I can retrieve all the items of all groups but it seems to be a little bit overkilling! I have searched in the code if there was some methods that are using the content/users/username/folderid/itemid URLs but I have only found something related to the status or about the sharing REST methods.

Cheers

**Comment by rwmajor2** [comment] 2018-03-24 12:12
Thanks @medspx.  I am closing this as a duplicate of #200.  Yes, this was an oversight in the API not to easily have a property to retrieve this information.  We have added a new 'shared_with' property that will be available in the next release.

**Closed by rwmajor2** 2018-03-24 12:12 UTC
