### ISSUE TITLE
Conda install -c esri arcgis not working !

### ISSUE THREAD

**Issue by PavlosDem99** [Esri/arcgis-python-api#1322] opened 2022-08-06 15:15 UTC
**Describe the bug**
I can't install Arcgis API with anaconda distribution. I insert at Anaconda Prompt in a new enviroment 
conda install -c esri arcgis
My virtual env called ArcGIS_API and I have not installed any other packages. 

error:
```UnsatisfiableError:
Note that strict channel priority may have removed packages required for satisfiability.
```
**Screenshots**
![image](https://user-images.githubusercontent.com/95135614/183254825-60e25e88-e64a-484d-9ed9-70f91248626f.png)

**Expected behavior**
I was expexted the installation of ArcGIS API.

**Platform (please complete the following information):**
 - OS: Windows 11

**Comment by nanaeaubry** [comment] 2022-08-24 22:38
What version of Python are you using?

**Comment by PavlosDem99** [comment] 2022-08-25 07:40
(base) C:\Users\pavlo> python --version

**Python 3.8.8**

**Comment by nanaeaubry** [comment] 2022-08-25 14:31
The only advice I could find was to add `-c conda-forge` in the request. Hopefully this can help? We are unable to reproduce the issue on our end so it might be an error with Anaconda setup

**Comment by PavlosDem99** [comment] 2022-08-26 11:40
I try again with **_pip install arcgis_**

The result:

`
(API_ARC) C:\Digital_Photogrammetry\API_ARC>pip install arcgis
Collecting arcgis
  Using cached arcgis-2.0.0-py2.py3-none-any.whl
Collecting requests-negotiate-sspi
  Using cached requests_negotiate_sspi-0.5.2-py2.py3-none-any.whl (7.1 kB)
Collecting pywin32>=223
  Downloading pywin32-304-cp310-cp310-win_amd64.whl (12.1 MB)
     ---------------------------------------- 12.1/12.1 MB 4.8 MB/s eta 0:00:00
Collecting ujson>=3
  Using cached ujson-5.4.0-cp310-cp310-win_amd64.whl (37 kB)
Collecting requests-gssapi
  Using cached requests_gssapi-1.2.3-py2.py3-none-any.whl
Collecting ipywidgets>=7
  Downloading ipywidgets-8.0.1-py3-none-any.whl (133 kB)
     ---------------------------------------- 133.7/133.7 kB 4.0 MB/s eta 0:00:00
Collecting cachetools
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting widgetsnbextension>=3
  Downloading widgetsnbextension-4.0.2-py3-none-any.whl (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 3.5 MB/s eta 0:00:00
Collecting matplotlib
  Downloading matplotlib-3.5.3-cp310-cp310-win_amd64.whl (7.2 MB)
     ---------------------------------------- 7.2/7.2 MB 4.3 MB/s eta 0:00:00
Collecting requests-toolbelt
  Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting requests-oauthlib
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting geomet
  Using cached geomet-0.3.0-py3-none-any.whl (28 kB)
Collecting urllib3<1.26.0,>=1.25.10
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting lxml
  Using cached lxml-4.9.1-cp310-cp310-win_amd64.whl (3.6 MB)
Collecting requests-kerberos
  Using cached requests_kerberos-0.14.0-py2.py3-none-any.whl (11 kB)
Collecting numpy>=1.16.2
  Downloading numpy-1.23.2-cp310-cp310-win_amd64.whl (14.6 MB)
     ---------------------------------------- 14.6/14.6 MB 2.5 MB/s eta 0:00:00
Collecting winkerberos
  Using cached winkerberos-0.9.0-cp310-cp310-win_amd64.whl (23 kB)
Collecting jupyterlab
  Using cached jupyterlab-3.4.5-py3-none-any.whl (8.8 MB)
Collecting keyring<=21.8.*,>=19
  Using cached keyring-21.7.0-py3-none-any.whl (32 kB)
Collecting pandas>=1
  Using cached pandas-1.4.3-cp310-cp310-win_amd64.whl (10.5 MB)
Collecting pyshp>=2
  Using cached pyshp-2.3.1-py2.py3-none-any.whl (46 kB)
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting python-certifi-win32
  Using cached python_certifi_win32-1.6.1-py2.py3-none-any.whl (7.3 kB)
Collecting lerc
  Using cached lerc-0.1.0-py3-none-any.whl
Collecting requests-ntlm
  Using cached requests_ntlm-1.1.0-py2.py3-none-any.whl (5.7 kB)
Collecting cryptography
  Using cached cryptography-37.0.4-cp36-abi3-win_amd64.whl (2.4 MB)
Collecting ipython>=6.1.0
  Downloading ipython-8.4.0-py3-none-any.whl (750 kB)
     ---------------------------------------- 750.8/750.8 kB 2.3 MB/s eta 0:00:00
Collecting traitlets>=4.3.1
  Downloading traitlets-5.3.0-py3-none-any.whl (106 kB)
     ---------------------------------------- 106.8/106.8 kB 2.1 MB/s eta 0:00:00
Collecting ipykernel>=4.5.1
  Downloading ipykernel-6.15.1-py3-none-any.whl (132 kB)
     ---------------------------------------- 132.9/132.9 kB 2.0 MB/s eta 0:00:00
Collecting jupyterlab-widgets~=3.0
  Downloading jupyterlab_widgets-3.0.2-py3-none-any.whl (383 kB)
     ---------------------------------------- 384.0/384.0 kB 2.7 MB/s eta 0:00:00
Collecting pywin32-ctypes!=0.1.0,!=0.1.1
  Using cached pywin32_ctypes-0.2.0-py2.py3-none-any.whl (28 kB)
Collecting pytz>=2020.1
  Using cached pytz-2022.2.1-py2.py3-none-any.whl (500 kB)
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting cffi>=1.12
  Downloading cffi-1.15.1-cp310-cp310-win_amd64.whl (179 kB)
     ---------------------------------------- 179.1/179.1 kB 414.8 kB/s eta 0:00:00
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting jupyter-server~=1.16
  Using cached jupyter_server-1.18.1-py3-none-any.whl (344 kB)
Collecting jinja2>=2.1
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ---------------------------------------- 133.1/133.1 kB 871.4 kB/s eta 0:00:00
Collecting jupyterlab-server~=2.10
  Downloading jupyterlab_server-2.15.1-py3-none-any.whl (54 kB)
     ---------------------------------------- 54.1/54.1 kB 1.4 MB/s eta 0:00:00
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting notebook<7
  Downloading notebook-6.4.12-py3-none-any.whl (9.9 MB)
     ---------------------------------------- 9.9/9.9 MB 1.7 MB/s eta 0:00:00
Collecting tornado>=6.1.0
  Downloading tornado-6.2-cp37-abi3-win_amd64.whl (425 kB)
     ---------------------------------------- 425.3/425.3 kB 3.8 MB/s eta 0:00:00
Collecting jupyter-core
  Downloading jupyter_core-4.11.1-py3-none-any.whl (88 kB)
     ---------------------------------------- 88.4/88.4 kB 2.5 MB/s eta 0:00:00
Collecting nbclassic
  Using cached nbclassic-0.4.3-py3-none-any.whl (9.7 MB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-9.2.0-cp310-cp310-win_amd64.whl (3.3 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp310-cp310-win_amd64.whl (55 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.37.1-py3-none-any.whl (957 kB)
     ---------------------------------------- 957.2/957.2 kB 4.0 MB/s eta 0:00:00
Collecting pyparsing>=2.2.1
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ---------------------------------------- 98.3/98.3 kB 5.5 MB/s eta 0:00:00
Collecting wrapt>=1.10.4
  Using cached wrapt-1.14.1-cp310-cp310-win_amd64.whl (35 kB)
Collecting certifi
  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
Collecting setuptools-scm
  Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting gssapi
  Downloading gssapi-1.8.1-cp310-cp310-win_amd64.whl (676 kB)
     ---------------------------------------- 676.7/676.7 kB 2.7 MB/s eta 0:00:00
Collecting pyspnego[kerberos]
  Downloading pyspnego-0.6.0-cp310-cp310-win_amd64.whl (234 kB)
     ---------------------------------------- 235.0/235.0 kB 1.4 MB/s eta 0:00:00
Collecting pypiwin32>=223
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Collecting ntlm-auth>=1.0.2
  Using cached ntlm_auth-1.5.0-py2.py3-none-any.whl (29 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.0-py3-none-any.whl (151 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting debugpy>=1.0
  Downloading debugpy-1.6.3-cp310-cp310-win_amd64.whl (4.6 MB)
     ---------------------------------------- 4.6/4.6 MB 3.7 MB/s eta 0:00:00
Collecting psutil
  Downloading psutil-5.9.1-cp310-cp310-win_amd64.whl (245 kB)
     ---------------------------------------- 245.8/245.8 kB 3.0 MB/s eta 0:00:00
Collecting jupyter-client>=6.1.12
  Downloading jupyter_client-7.3.5-py3-none-any.whl (132 kB)
     ---------------------------------------- 132.1/132.1 kB 3.9 MB/s eta 0:00:00
Collecting matplotlib-inline>=0.1
  Downloading matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting nest-asyncio
  Using cached nest_asyncio-1.5.5-py3-none-any.whl (5.2 kB)
Collecting pyzmq>=17
  Downloading pyzmq-23.2.1-cp310-cp310-win_amd64.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 3.6 MB/s eta 0:00:00
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-3.0.30-py3-none-any.whl (381 kB)
     ---------------------------------------- 381.7/381.7 kB 2.2 MB/s eta 0:00:00
Collecting jedi>=0.16
  Using cached jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
Collecting stack-data
  Downloading stack_data-0.4.0-py3-none-any.whl (23 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting colorama
  Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting pygments>=2.4.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 2.2 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=18.5 in c:\users\pavlo\anaconda3\envs\api_arc\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7->arcgis) (65.3.0)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1-cp310-cp310-win_amd64.whl (17 kB)
Collecting anyio<4,>=3.1.0
  Using cached anyio-3.6.1-py3-none-any.whl (80 kB)
Collecting websocket-client
  Downloading websocket_client-1.4.0-py3-none-any.whl (54 kB)
     ---------------------------------------- 54.7/54.7 kB 2.8 MB/s eta 0:00:00
Collecting pywinpty
  Downloading pywinpty-2.0.7-cp310-none-win_amd64.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 1.1 MB/s eta 0:00:00
Collecting nbconvert>=6.4.4
  Downloading nbconvert-7.0.0-py3-none-any.whl (271 kB)
     ---------------------------------------- 271.3/271.3 kB 314.9 kB/s eta 0:00:00
Collecting nbformat>=5.2.0
  Downloading nbformat-5.4.0-py3-none-any.whl (73 kB)
     ---------------------------------------- 73.3/73.3 kB 2.0 MB/s eta 0:00:00
Collecting argon2-cffi
  Using cached argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting terminado>=0.8.3
  Downloading terminado-0.15.0-py3-none-any.whl (16 kB)
Collecting prometheus-client
  Using cached prometheus_client-0.14.1-py3-none-any.whl (59 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting json5
  Using cached json5-0.9.10-py2.py3-none-any.whl (19 kB)
Collecting babel
  Using cached Babel-2.10.3-py3-none-any.whl (9.5 MB)
Collecting jsonschema>=3.0.1
  Downloading jsonschema-4.14.0-py3-none-any.whl (82 kB)
     ---------------------------------------- 82.4/82.4 kB 419.6 kB/s eta 0:00:00
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting notebook-shim>=0.1.0
  Using cached notebook_shim-0.1.0-py3-none-any.whl (13 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting sniffio>=1.1
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting attrs>=17.4.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp310-cp310-win_amd64.whl (61 kB)
     ---------------------------------------- 61.6/61.6 kB 1.7 MB/s eta 0:00:00
Collecting entrypoints
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting mistune<3,>=2.0.3
  Downloading mistune-2.0.4-py2.py3-none-any.whl (24 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting tinycss2
  Using cached tinycss2-1.1.1-py3-none-any.whl (21 kB)
Collecting bleach
  Downloading bleach-5.0.1-py3-none-any.whl (160 kB)
     ---------------------------------------- 160.9/160.9 kB 1.4 MB/s eta 0:00:00
Collecting defusedxml
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting pandocfilters>=1.4.1
  Using cached pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting jupyterlab-pygments
  Using cached jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)
Collecting nbclient>=0.5.0
  Downloading nbclient-0.6.7-py3-none-any.whl (71 kB)
     ---------------------------------------- 71.8/71.8 kB 1.9 MB/s eta 0:00:00
Collecting fastjsonschema
  Downloading fastjsonschema-2.16.1-py3-none-any.whl (22 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting argon2-cffi-bindings
  Using cached argon2_cffi_bindings-21.2.0-cp36-abi3-win_amd64.whl (30 kB)
Collecting asttokens
  Downloading asttokens-2.0.8-py2.py3-none-any.whl (23 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing
  Downloading executing-0.10.0-py2.py3-none-any.whl (17 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, wcwidth, Send2Trash, pywin32-ctypes, pywin32, pytz, pure-eval, pickleshare, mistune, json5, ipython-genutils, fastjsonschema, executing, backcall, wrapt, winkerberos, widgetsnbextension, websocket-client, urllib3, ujson, typing-extensions, traitlets, tornado, tomli, tinycss2, soupsieve, sniffio, six, pyzmq, pywinpty, pyshp, pyrsistent, pypiwin32, pyparsing, pygments, pycparser, psutil, prompt-toolkit, prometheus-client, pillow, parso, pandocfilters, oauthlib, numpy, ntlm-auth, nest-asyncio, MarkupSafe, lxml, lerc, kiwisolver, keyring, jupyterlab-widgets, jupyterlab-pygments, idna, fonttools, entrypoints, defusedxml, decorator, debugpy, cycler, colorama, charset-normalizer, certifi, cachetools, babel, attrs, terminado, requests, python-dateutil, packaging, matplotlib-inline, jupyter-core, jsonschema, jinja2, jedi, gssapi, click, cffi, bleach, beautifulsoup4, asttokens, anyio, stack-data, setuptools-scm, requests-toolbelt, requests-oauthlib, requests-negotiate-sspi, requests-gssapi, pandas, nbformat, matplotlib, jupyter-client, geomet, cryptography, argon2-cffi-bindings, requests-ntlm, python-certifi-win32, pyspnego, nbclient, ipython, argon2-cffi, nbconvert, ipykernel, requests-kerberos, notebook, jupyter-server, ipywidgets, notebook-shim, jupyterlab-server, nbclassic, jupyterlab, arcgis
Successfully installed MarkupSafe-2.1.1 Send2Trash-1.8.0 anyio-3.6.1 arcgis-2.0.0 argon2-cffi-21.3.0 argon2-cffi-bindings-21.2.0 asttokens-2.0.8 attrs-22.1.0 babel-2.10.3 backcall-0.2.0 beautifulsoup4-4.11.1 bleach-5.0.1 cachetools-5.2.0 certifi-2022.6.15 cffi-1.15.1 charset-normalizer-2.1.1 click-8.1.3 colorama-0.4.5 cryptography-37.0.4 cycler-0.11.0 debugpy-1.6.3 decorator-5.1.1 defusedxml-0.7.1 entrypoints-0.4 executing-0.10.0 fastjsonschema-2.16.1 fonttools-4.37.1 geomet-0.3.0 gssapi-1.8.1 idna-3.3 ipykernel-6.15.1 ipython-8.4.0 ipython-genutils-0.2.0 ipywidgets-8.0.1 jedi-0.18.1 jinja2-3.1.2 json5-0.9.10 jsonschema-4.14.0 jupyter-client-7.3.5 jupyter-core-4.11.1 jupyter-server-1.18.1 jupyterlab-3.4.5 jupyterlab-pygments-0.2.2 jupyterlab-server-2.15.1 jupyterlab-widgets-3.0.2 keyring-21.7.0 kiwisolver-1.4.4 lerc-0.1.0 lxml-4.9.1 matplotlib-3.5.3 matplotlib-inline-0.1.6 mistune-2.0.4 nbclassic-0.4.3 nbclient-0.6.7 nbconvert-7.0.0 nbformat-5.4.0 nest-asyncio-1.5.5 notebook-6.4.12 notebook-shim-0.1.0 ntlm-auth-1.5.0 numpy-1.23.2 oauthlib-3.2.0 packaging-21.3 pandas-1.4.3 pandocfilters-1.5.0 parso-0.8.3 pickleshare-0.7.5 pillow-9.2.0 prometheus-client-0.14.1 prompt-toolkit-3.0.30 psutil-5.9.1 pure-eval-0.2.2 pycparser-2.21 pygments-2.13.0 pyparsing-3.0.9 pypiwin32-223 pyrsistent-0.18.1 pyshp-2.3.1 pyspnego-0.6.0 python-certifi-win32-1.6.1 python-dateutil-2.8.2 pytz-2022.2.1 pywin32-304 pywin32-ctypes-0.2.0 pywinpty-2.0.7 pyzmq-23.2.1 requests-2.28.1 requests-gssapi-1.2.3 requests-kerberos-0.14.0 requests-negotiate-sspi-0.5.2 requests-ntlm-1.1.0 requests-oauthlib-1.3.1 requests-toolbelt-0.9.1 setuptools-scm-7.0.5 six-1.16.0 sniffio-1.2.0 soupsieve-2.3.2.post1 stack-data-0.4.0 terminado-0.15.0 tinycss2-1.1.1 tomli-2.0.1 tornado-6.2 traitlets-5.3.0 typing-extensions-4.3.0 ujson-5.4.0 urllib3-1.25.11 wcwidth-0.2.5 webencodings-0.5.1 websocket-client-1.4.0 widgetsnbextension-4.0.2 winkerberos-0.9.0 wrapt-1.14.1
`

Then, I open jupyter notebook

![image](https://user-images.githubusercontent.com/95135614/186894681-080de54e-19bb-4458-867d-2077cd758dc8.png)

So, i insert on a cell code at jupyter notebook 

import arcgis ##to check if it was working - The result of this was:

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\pavlo\\AppData\\Local\\Temp\\tmpphp66mj6'

**Comment by nanaeaubry** [comment] 2022-08-26 14:41
Interesting, I have not run into this before. I had to google a bit and it seems that this has to do with a system path error or a temp folder not being able to be deleted properly. Pretty much it is: "you have made an error in a place where the error is hidden from you"

Here are some other people who have had this issue in other scenarios, maybe one of these can help you find what to do:
https://github.com/Belval/pdf2image/issues/151

I would also recommend trying to do an `import arcgis` in your command prompt python and also in an IDE to see if it is specific to Jupyter Notebooks.

Hope that can help!

**Comment by PavlosDem99** [comment] 2022-08-26 17:53
Thanks a lot for your your help. I will check the tips and the refferneces you gave me to see what else is going on

**Comment by nanaeaubry** [comment] 2022-08-26 17:55
Great closing this issue since we can't do much more but feel free to comment again if needed! :)

**Closed by nanaeaubry** 2022-08-26 17:55 UTC
Labels: bug
