### ISSUE TITLE
clone_items crash when cloning ArcGIS Portal Version 3.10 Enterprise Version 10.4.1

### ISSUE THREAD

**Issue by Hlindemann** [Esri/arcgis-python-api#605] opened 2020-02-20 05:52 UTC
**Describe the bug**
When Cloning WebMap WebApp etc.. from ArcGIS Enteterprise 10.4.1 to 10.5.1 the clone tool crashes with the following error 
int() argument must be a string, a bytes-like object or a number, not 'NoneType'", None

**To Reproduce**
```python
from arcgis.gis import GIS
import logging
import json
logging.basicConfig(level=logging.DEBUG)

source_owner = ''
target_owner = ''
src_url = ''
src_username = ''
src_password = ''

dst_url = ""
dst_username = ''
dst_password =''
source = GIS(src_url, src_username, src_password)
target = GIS(dst_url, dst_username, dst_password)
print("Connected to Source and Target Portals")


users = source.users.search(source_owner)

app = source.content.get('7fe00d08238a495da4ea5226c51dac22')
data = [app]
folder = ''
target.content.clone_items(data, copy_data=False, folder=folder, search_existing_items=True)

```
error:
```python
int() argument must be a string, a bytes-like object or a number, not 'NoneType'", None
```
**Screenshots**

**Expected behavior**
The Item to be Cloned

**Platform (please complete the following information):**
 - OS: Windows Server 2012 R2
 - Browser N\A
 - Python API Version 1.7.1

**Additional context**
Upon Investigation I found that in the __init__.py a call is made to 'content/items/' + self._item.itemid + '/resources' but the api at version 3.10 does not have 'nextStart'  in the api

    
![image](https://user-images.githubusercontent.com/21313366/74904890-a7587680-53b5-11ea-8bce-ef03b9932133.png)
```python
query_url = 'content/items/' + self._item.itemid + '/resources'
        params = {'f':'json',
                  'num': 1000}
        resp = self._portal.con.get(query_url, params)
        resp_resources = resp.get('resources')
        count = int(resp.get('num'))


# My Temp Fix
        if 'nextStart' not in resp:
            resp['nextStart'] = -1
        next_start = int(resp.get('nextStart'))

**Comment by achapkowski** [comment] 2020-02-25 10:49
The issue is fixed in the next release which will be release in March 2020.  Thank you for reporting.

**Closed by achapkowski** 2020-02-25 10:49 UTC
Labels: fixed, under consideration

**Comment by Hlindemann** [comment] 2020-02-25 13:42
Great Thank you Andrew
