### ISSUE TITLE
Python for ArcGIS 1.9.0 and ArcPy 2.8 incompatibility? (pandas)

### ISSUE THREAD

**Issue by PeterReyne** [Esri/arcgis-python-api#1094] opened 2021-09-09 04:29 UTC
**Describe the bug**
Cross post from the forums after another user verified:
https://community.esri.com/t5/arcgis-api-for-python-questions/python-for-arcgis-1-9-0-and-arcpy-2-8/m-p/1095827#M6592

We have found that there may be an issue with the pandas install when using Python for ArcGIS 1.9.0 and ArcPy 2.8 together in a conda clone. Posting to see if it affects and/or helps others.

I am using Conda 4.10.0 and ArcGIS Pro 2.8.2 is installed on the machine.

**To Reproduce**
New clone, install Python for ArcGIS 1.9.0 (works ok at this time)

```
conda create -c esri -n arcgis-pro --yes --offline python=3.7
conda install -c esri --yes --offline arcgis=1.9.0
conda activate arcgis-pro python
>>> import arcgis
>>>
>>> exit()
```

Install ArcPy 2.8 (breaks Python for ArcGIS 1.9.0)

```
conda install -c esri --yes --offline arcpy=2.8
python
>>> import arcgis
>>> !!explosions!! (see error below)
```

**Error**
If pandas is not upgraded/reinstalled after installing ArcPy 2.8, we received the following error when attempting to use Python for ArcGIS 1.9.0

```
(arcgis-pro) PS D:\> python
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import arcgis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\__init__.py", line 4, in <module>
    from . import features, geoanalytics, geocoding, geometry
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\features\__init__.py", line 33, in <module>
    from . import enrich_data
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\features\enrich_data.py", line 10, in <module>
    import arcgis.network as network
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\network\__init__.py", line 7, in <module>
    from ._layer import (
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\network\_layer.py", line 10, in <module>
    from arcgis.mapping import MapImageLayer
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\mapping\__init__.py", line 8, in <module>
    from ._types import (
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\mapping\_types.py", line 30, in <module>
    from arcgis.widgets._mapview._traitlets_extension import ObservableDict
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\widgets\__init__.py", line 2, in <module>
    from arcgis.widgets._mapview import MapView
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\widgets\_mapview\__init__.py", line 1, in <module>
    from arcgis.widgets._mapview._mapview import MapView
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\arcgis\widgets\_mapview\_mapview.py", line 38, in <module>
    import pandas as pd
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import (
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\pandas\compat\__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\pandas\compat\pyarrow.py", line 9, in <module>
    _palv = Version(_pa_version)
  File "C:\ProgramData\Anaconda3\envs\arcgis-pro27\lib\site-packages\pandas\util\version\__init__.py", line 339, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

**Expected behavior**
The following works (update pandas):

```
conda create -c esri -n arcgis-pro --yes --offline python=3.7
conda install -c esri --yes --offline arcgis=1.9.0
conda install -c esri --yes --offline arcpy=2.8
conda install -c anaconda --yes --offline pandas=1.1.3
```

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 1.9.0
 - Conda Version: 4.10.1
 - ArcPy Version: 2.8
 - ArcGIS Pro Version Installed: 2.8.2

**Additional context**
Only occurs when combined with ArcPy 2.8 in a conda clone.

**Comment by AtmaMani** [comment] 2021-09-10 21:50
@PeterReyne I am not able to reproduce this issue. Can you try this instead from Python Command Prompt?

```
conda create -n arcpro_clone
activate arcpro_clone
conda install -c esri arcpy
ipython

In [1]: import arcgis  # no errors
In [2]: import pandas as pd  # no errors
In [3]: import arcpy    # no errors here as well
```
**Notes**
 - When creating a conda env, unless you have a strict requirement of a Python version, create the env without specifying the Python version (as above). The first package you install will dictate the interpreter and version.
 - Install the biggest package or package with greatest set of dependencies first (in this case arcpy). This will help the conda suitability solver run faster, goes with point 1 above.
 - Installing arcpy will pull the latest Python API version that satisfies arcpy's pinning requirements (1.9.0 in this case)

**Comment by AtmaMani** [comment] 2021-09-15 22:10
Closing this issue since its not reproducible. If you still have this issue, please reopen

**Closed by AtmaMani** 2021-09-15 22:10 UTC
Labels: bug
