### ISSUE TITLE
item.share() Sharing as True if string value provided

### ISSUE THREAD

**Issue by BrettFrahm** [Esri/arcgis-python-api#1624] opened 2023-07-31 21:05 UTC
**Describe the bug**
The share() function on items in the documentation states that the public= and org= parameters accepts boolean inputs. The tool will not error out if you use text inputs, it still runs. Unfortunately since it runs with string inputs, if you have an org parameter of string 'False' it will interpret it as a boolean True. All of my organization's content is now shared organization wide because of this.

If you use item.share(org='False') your item will be shared to the organization if it was previously only shared privately.

**To Reproduce**
```python
item.share(org='False')
```
error:
No error messages, which is part of the issue. If the function parameters require a boolean to work, it should not allow strings at all. If you enter a string an exception should be raised.

**Expected behavior**
An error with share() not running.

**Platform (please complete the following information):**
 - OS: Windows
 - Python API Version: 2.0.1

**Comment by nanaeaubry** [comment] 2023-08-02 07:48
@BrettFrahm 
I see what you mean with no error being returned, we can look at that. But I am unable to reproduce where 'False' is taken as True. 

 Are you using ArcGIS Enterprise or ArcGIS Online?

**Comment by BrettFrahm** [comment] 2023-08-02 13:51
@nanaeaubry thank you for looking into this. I have only tested in ArcGIS Online. I just tested again and I have some clarification on how to reproduce.

This does not reproduce the issue
`item.share(org='False')`

Adding public='False' does. This will set the sharing to organization.
`item.share(public='False', org='False')`

**Comment by nanaeaubry** [comment] 2023-08-02 14:45
@BrettFrahm 
Ah ha! I definitely see that bug. If something is passed in for public we assume it was True and not False and set the org to True.
We will take care of it, thank you :)

**Comment by nanaeaubry** [comment] 2023-08-18 11:35
This has been fixed and will be in the September 2.2.0 release

**Closed by nanaeaubry** 2023-08-18 11:35 UTC
Labels: bug
