### ISSUE TITLE
DeprciationWarning on Numpy 1.20

### ISSUE THREAD

**Issue by cylussec** [Esri/arcgis-python-api#1090] opened 2021-08-24 19:44 UTC
**Describe the bug**
With Numpy 1.20, there are parts of arcgis that are getting deprication warnings. 

**To Reproduce**
```python
from arcgis.gis import GIS 

GIS()
```
error:
```python
.tox/py39/lib/python3.9/site-packages/arcgis/features/_data/geodataset/utils.py:21
  /home/runner/work/atves/atves/.tox/py39/lib/python3.9/site-packages/arcgis/features/_data/geodataset/utils.py:21: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.int,

.tox/py39/lib/python3.9/site-packages/arcgis/features/_data/geodataset/utils.py:25
  /home/runner/work/atves/atves/.tox/py39/lib/python3.9/site-packages/arcgis/features/_data/geodataset/utils.py:25: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.float,

.tox/py39/lib/python3.9/site-packages/arcgis/features/_data/geodataset/utils.py:34
  /home/runner/work/atves/atves/.tox/py39/lib/python3.9/site-packages/arcgis/features/_data/geodataset/utils.py:34: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    STRING_TYPES = tuple([str] + [str, np.str, np.unicode, chr])

.tox/py39/lib/python3.9/site-packages/arcgis/features/_data/geodataset/utils.py:34
  /home/runner/work/atves/atves/.tox/py39/lib/python3.9/site-packages/arcgis/features/_data/geodataset/utils.py:34: DeprecationWarning: `np.unicode` is a deprecated alias for `np.compat.unicode`. To silence this warning, use `np.compat.unicode` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `str` for which `np.compat.unicode` is itself an alias. Doing this will not modify any behaviour and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    STRING_TYPES = tuple([str] + [str, np.str, np.unicode, chr])

.tox/py39/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py:284
  /home/runner/work/atves/atves/.tox/py39/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py:284: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
    max_retries=Retry(
```
**Screenshots**

**Expected behavior**
There should not be warnings

**Platform (please complete the following information):**
 - OS:  Windows
 - Browser [e.g. chrome, safari] NA
 - Python API Version [e.g. `1.6.2`] 3.9.x

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by achapkowski** [comment] 2021-08-25 10:38
@cylussec warnings are not errors.  They provide information that the libraries you are using are changing.  We are aware of these messages.  To disable the warnings, please do:

To suppress all warnings, you can do this if you want:

```python
import warnings
warnings.filterwarnings("ignore")
```

This is probably better:

```
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    <logic that causes the warning>
```

Hope this helps.

**Comment by cylussec** [comment] 2021-08-25 11:48
Of course. I just didn't see an existing ticket about this.

**Comment by AtmaMani** [comment] 2021-09-01 21:11
I too am unable to reproduce these warnings. I tried with a couple of different environments with numpy versions 1.21 as well as 1.20.3. Since this is not a bug, has a workaround and does not hinder any workflows, I am closing this issue. 

But thanks for reporting this and I do see NumPy's deprecation on their website. So I will log an enhancement for us to consider for future releases.

**Closed by AtmaMani** 2021-09-01 21:11 UTC
Labels: enhancement
