### ISSUE TITLE
User Delete 1.8.5 Error

### ISSUE THREAD

**Issue by mamesser** [Esri/arcgis-python-api#1009] opened 2021-05-18 18:50 UTC
**Describe the bug**
user.delete() returns not licensed by user (Error code: 400) - See attachment

**To Reproduce**
```python
auth = arcgis.gis.GIS(domain,user,pwd)
user = arcgis.gis.User(auth,username=username)
user.delete()
```
error:
see attachment

**Screenshots**
![deleteUserError](https://user-images.githubusercontent.com/7096492/118706302-70e6f280-b7d6-11eb-97df-8bde388ee270.png)

**Expected behavior**
User would be deleted.

**Platform (please complete the following information):**
 - OS: Windows 10.0.18363
 - Browser: NA
 - Python API Version: 1.8.5 ; Also see below.

**Additional context**
See [original Esri community post](https://community.esri.com/t5/arcgis-api-for-python-questions/user-delete-not-licensed-by-user-error/m-p/1055907/thread-id/6029#M6030)
Versions tested with error: ArcGIS Pro 2.7.0 Python API 1.8.4; ArcGIS Pro 2.7.3 Python API 1.8.5;
Working version: ArcGIS Pro 2.3.2 Python API 1.6.2;  and can delete using AGOL web interface.

**Comment by cvricella2** [comment] 2021-06-21 14:21
This going to get fixed anytime soon? @EsriGithub

**Comment by AtmaMani** [comment] 2021-09-15 22:57
@mamesser I read through this and the conversation on GeoNet. My suspicion is the account that you are using to delete (`auth` in your script) may not have sufficient privileges for the operation. The error may not have to do with licenses held by the user to be deleted.

At any rate, I created a dummy user in my AGO org and was able to successfully delete it using Python API 1.9.1 (which will be released in a month).

I am closing this issue for now as I cannot reproduce using the same steps you followed. Please reopen if this is not resolved with 1.9.1

**Closed by AtmaMani** 2021-09-15 22:57 UTC
Labels: bug

**Comment by mamesser** [comment] 2021-09-15 23:32
Thanks @AtmaMani. I will test when the new version is released. To verify, the account I was using was an administrator, thus had sufficient privileges. This was the same account used to verify the user.delete had worked at version 1.6.2. Given the ease in creating virtual environments for testing, is there a reason beyond workload not to test the version exhibiting the error?

**Comment by AtmaMani** [comment] 2021-09-17 06:14
@mamesser thank you. Regarding testing older versions, it is more of a business decision. Esri is by-and-large moving away from hot fixes and patches and tries to encourage users to migrate to newer versions where it will address the bugs. Having said that, we will support users that cannot upgrade, as long as the version is under support (See PLC at https://support.esri.com/en/Products/Developers/scripting-and-automation/arcgis-api-for-python/1-9#product-support).
