### ISSUE TITLE
Cannot use the map widget in Jupyter Notebook/ ArcGIS Notebook in ArcGIS Online

### ISSUE THREAD

**Issue by samuello4** [Esri/arcgis-python-api#835] opened 2020-11-19 06:50 UTC
Got an error message when using the map widget in Jupyter Notebook/ ArcGIS Notebook in ArcGIS Online.  
![Capture](https://user-images.githubusercontent.com/42732361/99631397-7b6a3e80-2a76-11eb-8c97-eacc9f15d097.PNG)

**Comment by achapkowski** [comment] 2020-11-19 10:47
@samuello4 thank you for reporting this, we are looking into it.

**Comment by mhweber** [comment] 2020-11-19 16:10
Same issue with map widget in Jupyter Notebook in ArcPro as well

**Comment by kadebeem** [comment] 2020-11-19 17:13
Also seeing this in Notebook Server 10.8.1

**Comment by achapkowski** [comment] 2020-11-19 17:17
What browser is everyone using?  @kadebeem @mhweber @samuello4

**Comment by kadebeem** [comment] 2020-11-19 17:23
Google Chrome. Ah, wonder if it's the recent chrome update that's throwing things off. I just tried in Firefox as well. Same problem.

**Comment by achapkowski** [comment] 2020-11-19 17:24
Can you try the Edge Chromium version? Just to cover the whole group.

**Comment by DavidJVitale** [comment] 2020-11-19 17:25
As @achapkowski said, we are looking into fixing a permanent fix. If anyone need a map widget working right now, try this for an (experimental) workaround:

- Restart your kernel and clear all output
- Refresh your browser
- Run this code in a cell BEFORE YOU DRAW ANY MAP:
- ```python
   from arcgis.widgets import MapView
   MapView.set_js_cdn("https://js.arcgis.com/4.18/")
  ```

Disclaimer: The JavaScript API version 4.18 is in beta and has not been formally released yet. The Python API map widget has been certified against version 4.15, not against this beta 4.18. Not all functionality may work.

**Comment by kadebeem** [comment] 2020-11-19 17:34
@achapkowski Same issue in the chromium flavor of Edge. Tried @DavidJVitale workaround. Displayed loading icon at the top of the cell output, but never finished loading

`from arcgis.widgets import MapView
MapView.set_js_cdn("https://js.arcgis.com/4.18/")`

`map_1 = gis.map('California', zoomlevel=5)
map_1`

**Comment by DavidJVitale** [comment] 2020-11-19 22:55
@samuello4 @mhweber @kadebeem This was caused by a bug introduced in the JS API CDN at https://js.arcgis.com/4.15/ . That bug has since been fixed; the map should display now without any workarounds. Please clear your browser cache and try again. 

Closing. Please comment on this issue if you are still experiencing issues and we will happily help you resolve them. Thanks for bringing this to our attention.

**Closed by DavidJVitale** 2020-11-19 22:55 UTC
Labels: bug

**Comment by Naeemkh** [comment] 2021-10-29 19:17
@DavidJVitale, I am getting the same error. On both macOS and Windows 10. Tried all possible solutions, but no success. Please let me know if you need more information.
