### ISSUE TITLE
Error 498: Invalid Token GIS(logged in user) 

### ISSUE THREAD

**Issue by ebarrindep** [Esri/arcgis-python-api#1058] opened 2021-07-13 20:01 UTC
**Describe the bug**

**To Reproduce**
```python
<import os, sys, sqlite3
import arcpy
from arcgis import GIS
from arcgis.features import GeoAccessor, GeoSeriesAccessor, SpatialDataFrame, FeatureLayer
from IPython.display import display
from IPython.display import HTML
import numpy as np
import sqlalchemy as sa
from sqlalchemy import create_engine
from collections import OrderedDict, defaultdict, namedtuple
import pathlib
import urllib.parse
from functools import reduce
import pprint as pp
import pandas as pd
import getpass

printer = pp.PrettyPrinter()

# get username and password as variables using user prompt
user = input(prompt='Enter your username (city email)')
pwd = getpass.getpass(prompt='Enter your password for ArcGIS Online')

# create connection to organization
gis = GIS(url="https://independence.maps.arcgis.com/", username=user, password=pwd )
print("portal credentials connected through pro authentiction to licensing portal")

#create variable for parcels layer from County
parcels = FeatureLayer("https://jcgis.jacksongov.org/arcgis/rest/services/Cadastral/Parcel_Viewer_Layers/FeatureServer/18")
parcels

# create SEDF from parcels feature layer
sdf = parcels.query(as_df=True)

Exception: Invalid Token
(Error Code: 498)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-7-793e551f54b4> in <module>
----> 1 sdf = parcels.query(as_df=True)

in query(self, where, out_fields, time_filter, geometry_filter, return_geometry, return_count_only, return_ids_only, return_distinct_values, return_extent_only, group_by_fields_for_statistics, statistic_filter, result_offset, result_record_count, object_ids, distance, units, max_allowable_offset, out_sr, geometry_precision, gdb_version, order_by_fields, out_statistics, return_z, return_m, multipatch_option, quantization_parameters, return_centroid, return_all_records, result_type, historic_moment, sql_format, return_true_curves, return_exceeded_limit_features, as_df, datum_transformation, **kwargs)
   1545 
   1546         params['returnCountOnly'] = True
-> 1547         record_count = self._query(url, params, raw=as_raw)
   1548         if 'maxRecordCount' in self.properties:
   1549             max_records = self.properties['maxRecordCount']


   2561 
   2562             else:
-> 2563                 raise queryException
   2564 
   2565         def is_true(x):


   2531         try:
   2532             result = self._con.post(path=url,
-> 2533                                     postdata=params, token=self._token)
   2534         except Exception as queryException:
   2535             error_list = ["Error performing query operation", "HTTP Error 504: GATEWAY_TIMEOUT"]


    718                                      file_name=file_name,
    719                                      try_json=try_json,
--> 720                                      force_bytes=kwargs.pop('force_bytes', False))
    721     #----------------------------------------------------------------------
    722     def put(self, url, params=None, files=None, **kwargs):

    512                     return data
    513                 errorcode = data['error']['code'] if 'code' in data['error'] else 0
--> 514                 self._handle_json_error(data['error'], errorcode)
    515             return data
    516         else:


    534 
    535         errormessage = errormessage + "\n(Error Code: " + str(errorcode) +")"
--> 536         raise Exception(errormessage)
    537     #----------------------------------------------------------------------
    538     def post(self,

Exception: Invalid Token
(Error Code: 498)
>

**Comment by achapkowski** [comment] 2021-07-13 23:50
What version of the API are you using?

**Comment by achapkowski** [comment] 2021-07-14 10:58
@ebarrindep at the current release: `1.9.0` I cannot reproduce your issue:
![image](https://user-images.githubusercontent.com/5131271/125610917-b3c13750-7bf7-4bce-b77c-0eaf59eaa996.png)

and here is the data on a map:

![image](https://user-images.githubusercontent.com/5131271/125610978-d32d4272-4772-4619-8f05-f4049d0b5ae3.png)


I suggest you update your install of the ArcGIS API for Python to 1.9.0.

To do that, please read: https://pro.arcgis.com/en/pro-app/latest/arcpy/get-started/work-with-python-environments.htm 

Once cloned, install the 1.9.0 version of the ArcGIS API for Python.

**Comment by ebarrindep** [comment] 2021-07-14 17:05
I currently have arcgis 1.8.5 installed.   what is the difference between 1.8.5 and 1.9?

**Comment by achapkowski** [comment] 2021-07-14 18:05
@ebarrindep quite a bit, please see: https://developers.arcgis.com/python/guide/release-notes/

**Comment by achapkowski** [comment] 2021-08-24 10:53
closing due to not being able to reproduce the issue.

**Closed by achapkowski** 2021-08-24 10:53 UTC
Labels: cannot reproduce
