### ISSUE TITLE
query ignores result_record_count (and skips some items) if larger than max return count

### ISSUE THREAD

**Issue by JesseRussell411** [Esri/arcgis-python-api#2027] opened 2024-09-11 21:58 UTC
**Describe the bug**
_impl.common._query ignores result_record_count if it has to paginate.

For example if you call `query(where="1=1", result_record_count=10000, return_all_features=False)`, assuming 10000 is greater than the max record count of whatever you're querying, instead of return 10000 items, it just returns as many as it can.

This is visible in the code.
```
        # If none of the ifs above worked then keep going to find more features
        # Make sure we have all features
        if "exceededTransferLimit" in result:
            while (
                "exceededTransferLimit" in result
                and result["exceededTransferLimit"] == True
            ):
                if "resultRecordCount" not in params:
                    # assign initial value after first query
                    params["resultRecordCount"] = 2000
                if "resultOffset" in params:
                    # add the number we found to the offset so we don't have doubles
                    params["resultOffset"] = params["resultOffset"] + len(
                        result["features"]
                    )
                else:
                    # initial offset after first query (result record count set by user or up above)
                    params["resultOffset"] = params["resultRecordCount"]

                result = layer._con.post(path=url, postdata=params, token=layer._token)
                # add new features to the list
                features = features + result["features"]
```
There's no check for when resultRecordCount has been reached. It just pulls until exceededTranferLimit is false.

Also, if result result_record_count exceeds the max return count, causing the first request to return less than result_record_count items, a number of items are skipped because resultOffset gets set to resultRecordCount on the first iteration of the pagination loop (`params["resultOffset"] = params["resultRecordCount"]`), instead of the number of features returned so far (`len(features)`).

**To Reproduce**
```python
layer_or_table_object.query(result_record_count=10000, return_all_record=False) # just make sure result_record_count is greater than the maximun return count.
```
error:
Incorrect behavior. Instead of returning up to resultRecordCount items, the whole query is returned and some of the query is skipped.

**Expected behavior**
For the query to only return number of values equal to result_record_count.

**Platform (please complete the following information):**
 - OS: windows 10
 - Browser N/A
 - Python API Version  2.3.1

**Additional context**
Add any other context about the problem here, attachments etc.

edit: made it more clear that I'm talking about the result_record_count param of the query function on layers and tables.

**Comment by JesseRussell411** [comment] 2024-09-11 22:04
I actually tried re-writing this section of the source code and this seems to work pretty well.
```
if "exceededTransferLimit" in result and result["exceededTransferLimit"]:
    original_result_record_count = (
        params["resultRecordCount"] if "resultRecordCount" in params else None
    )
    original_result_offset = params["resultOffset"] if "resultOffset" in params else 0

    while "exceededTransferLimit" in result and result["exceededTransferLimit"]:
        if original_result_record_count is not None:
            params["resultRecordCount"] = original_result_record_count - len(features)
            if params["resultRecordCount"] <= 0:
                break

        params["resultOffset"] = len(features) + original_result_offset

        result = layer._con.post(path=url, postdata=params, token=layer._token)

        features += result["features"]
```

**Comment by JesseRussell411** [comment] 2024-09-12 12:26
> By not exceeding the transfer limit you've reached the resultRecordCount. So this is not a problem by itself.

That's if resultRecordCount doesn't exceed the transfer limit.

If pagination happens, each iteration of the loop uses the user's provided resultRecordCount as the requests resultRecordCount, if one was provided. It's never reduced to account for the increased resultOffset, so the window of returned results just keeps moving forward through the query until it reaches the end.

for example:

Assuming the user asks for a resultRecordCount of 5000 and the transfer limit is 2000:

 - first request:
   - offset 0
   - recordcount 5000
   - result: 2000 items (max returned)
   - exceededTransferLimit? true
   - totalitems: 2000
 
- first loop:
  - offset 5000 (`params["resultOffset"] = params["resultRecordCount"]`)
  - recordcount still 5000
  - result: 2000 items 
  - exceededTranferLimit? true
  - totalitems: 4000
 
- second loop:
  - offset 7000
    - ```
      if "resultOffset" in params:
          # add the number we found to the offset so we don't have doubles
          params["resultOffset"] = params["resultOffset"] + len(
              result["features"]
          )
      ```
  - recordcount still 5000
  - result: 2000 items 
  - exceededTranferLimit? true
  - totalitems: 6000
 

- third loop:
  - offset 9000 (7000 + 2000)
  - recordcount still 5000
  - result: 2000 items 
  - exceededTranferLimit? true
  - totalitems: 8000
 
- fourth loop:
  - offset 11000 (9000 + 2000)
  - recordcount still 5000
  - result: 2000 items 
  - exceededTranferLimit? true
  - totalitems: 10000
 
- etc

Of course, I'm only stepping through the code manually. I'm not able to test this at the moment.

Also, unless I've made a mistake somewhere, this also means that 3000 items where skipped because of this section:

```
if "resultOffset" in params:
        # add the number we found to the offset so we don't have doubles
        params["resultOffset"] = params["resultOffset"] + len(
            result["features"]
        )
    else:
        # initial offset after first query (result record count set by user or up above)
        params["resultOffset"] = params["resultRecordCount"]     #<---- if resultOffset not in params and resultRecordCount in params, resultOffset become resultRecordCount
```

This doesn't work if resultRecordCount is greater than the transfer limit.

**Comment by JesseRussell411** [comment] 2024-09-12 12:38
> The problem is that the code as written in the current version 2.3.1 does not pay attention to the default maxRecord that can/will be returned by the first query of the service.

That is also a problem, but is it even necessary to set an appropriate resultRecordCount, equal to maxRecord? Does it do any harm to cause "exceedTransferLimit" to be true? It seems to be the subject of the while loop. Not exceeding the transfer limit will cause the loop to stop.

My code just asks to exactly how many items it want in each iteration, (user provided resultRecordCount - items returned so far).

If there is harm in it, then I think this section needs to be rethought.

**Comment by JesseRussell411** [comment] 2024-09-12 13:21
Is "exceedTransferLimit" true if resultRecordCount was _equal_ to the transfer limit, but not actually _exceeding_ it? Otherwise, I don't see how this code can work, since it starts asking for 2000 items, which it assumes to be the transfer limit.

This is probably why I had to add a check to see if resultRecordCount is 0 in the code I wrote, since that shouldn't be necessary if the loops stopped once the transfer limit was no longer exceeded.

**Comment by HDO-B** [comment] 2024-09-13 05:38
> > The problem is that the code as written in the current version 2.3.1 does not pay attention to the default maxRecord that can/will be returned by the first query of the service.
> 
> That is also a problem, but is it even necessary to set an appropriate resultRecordCount, equal to maxRecord? Does it do any harm to cause "exceedTransferLimit" to be true? It seems to be the subject of the while loop. Not exceeding the transfer limit will cause the loop to stop.
> 
> My code just asks to get exactly how many items it wants in each iteration, (user provided resultRecordCount - items returned so far).
> 
> If there is harm in it, then I think this section needs to be rethought.

Current code does not check how many items are returned in the first query, only if the query has more result features than the service can provide in a single request returning an `exceedTransferLimit = True`. This is working perfectly fine until the code sets the `resultRecordCount` for the next query on a default 2k and with a 2k offset. This will cause errors with services who returns more features on the first query, or who has a maxRecord of less then 2k.

**Comment by HDO-B** [comment] 2024-09-13 05:47
> Is "exceedTransferLimit" true if resultRecordCount was _equal_ to the transfer limit, but not actually _exceeding_ it? Otherwise, I don't see how this code can work, since it starts asking for 2000 items, which it assumes to be the transfer limit.
> 
> This is probably why I had to add a check to see if resultRecordCount is 0 in the code I wrote, since that shouldn't be necessary if the loops stopped once the transfer limit was no longer exceeded.

`exceedTransferLimit` wil be set to true if the amount of features returned from the query are more than the maxRecords the service can return in a single request. If the query results in 2k features, and the service has a maxRecord of 2k features. The limit will not be exceeded thus `exceedTransferLimit` will be false.

The code was optimized in this release so the query is made first without checking if pagination is needed. This way the function will return the result of the first query if the `exceedTransferLimit` is `false` without the need of performing extra checks and running extra lines of code. 

If `exceedTransferLimit = True` it will go into the while loop until the service requests will return `exceedTransferLimit = False` This notifies the code that the last batch of features are returned and ends the loop. 

The problem arises when the code assumes a maxRecord of 2k instead of checking the first query results, or the service settings. Which is what the code did prior to `2.3`

**Comment by JesseRussell411** [comment] 2024-09-13 17:44
> The problem arises when the code assumes a maxRecord of 2k instead of checking the first query results, or the service settings. Which is what the code did prior to `2.3`

I'm not disagreeing with you. That is definitely a problem. I'm just saying it's not the only problem and isn't the subject of this issue and fixing it will not fix the problem I've brought up.

What this issue is about is that the code does not properly handle the scenario where the result_record_count given to the query function exceeds the transfer limit.

For example, if I query a FeatureLayer with a max return count of 1000 using a result_record_count of 3000. This is what happens:

I added some print statements to log the states of resultRecordCount and resultOffset

![image](https://github.com/user-attachments/assets/9326096e-4a55-41dd-b0d8-3a5325af5d91)

![image](https://github.com/user-attachments/assets/679dfe2d-f34f-4a12-a26d-7dc6bea64864)

Here's the query. Note that I remembered to set return_all_records=False
![image](https://github.com/user-attachments/assets/7efdc56e-2a26-424e-b5e9-77617b86c25c)

And this is the result:

```
after exceeding transfer limit: len(features)=1000
params['resultRecordCount']=3000 params['resultOffset']=3000
result['exceededTransferLimit']=True len(features)=2000
params['resultRecordCount']=3000 params['resultOffset']=4000
result['exceededTransferLimit']=True len(features)=3000
params['resultRecordCount']=3000 params['resultOffset']=5000
result['exceededTransferLimit']=True len(features)=4000
params['resultRecordCount']=3000 params['resultOffset']=6000
result['exceededTransferLimit']=True len(features)=5000
params['resultRecordCount']=3000 params['resultOffset']=7000
result['exceededTransferLimit']=True len(features)=6000
params['resultRecordCount']=3000 params['resultOffset']=8000
result['exceededTransferLimit']=True len(features)=7000
params['resultRecordCount']=3000 params['resultOffset']=9000
result['exceededTransferLimit']=True len(features)=8000
params['resultRecordCount']=3000 params['resultOffset']=10000
result['exceededTransferLimit']=True len(features)=9000
params['resultRecordCount']=3000 params['resultOffset']=11000
result['exceededTransferLimit']=True len(features)=10000
params['resultRecordCount']=3000 params['resultOffset']=12000
result['exceededTransferLimit']=True len(features)=11000
params['resultRecordCount']=3000 params['resultOffset']=13000
result['exceededTransferLimit']=True len(features)=12000
params['resultRecordCount']=3000 params['resultOffset']=14000
result['exceededTransferLimit']=True len(features)=13000
params['resultRecordCount']=3000 params['resultOffset']=15000
result['exceededTransferLimit']=True len(features)=14000
params['resultRecordCount']=3000 params['resultOffset']=16000
result['exceededTransferLimit']=True len(features)=15000
params['resultRecordCount']=3000 params['resultOffset']=17000
result['exceededTransferLimit']=True len(features)=16000
params['resultRecordCount']=3000 params['resultOffset']=18000
result['exceededTransferLimit']=True len(features)=17000
params['resultRecordCount']=3000 params['resultOffset']=19000
result['exceededTransferLimit']=True len(features)=18000
params['resultRecordCount']=3000 params['resultOffset']=20000
result['exceededTransferLimit']=True len(features)=19000
params['resultRecordCount']=3000 params['resultOffset']=21000
result['exceededTransferLimit']=True len(features)=20000

*stopped with ctrl+c
```

**Comment by JesseRussell411** [comment] 2024-09-13 19:59
> `exceedTransferLimit` wil be set to true if the amount of features returned from the query are more than the maxRecords the service can return in a single request. If the query results in 2k features, and the service has a maxRecord of 2k features. The limit will not be exceeded thus `exceedTransferLimit` will be false.

Actually. I seem to have run into something very strange. exceededTransferLimit seems to be true regardless of resultRecordCount.

For example, with this query:
https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/NDGD_SmokeForecast_v1/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&relationParam=&returnGeodetic=false&outFields=&returnGeometry=false&returnCentroid=false&returnEnvelope=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&defaultSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=1&returnZ=false&returnM=false&returnTrueCurves=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=html&token=

I set format to json and got this:
![image](https://github.com/user-attachments/assets/f234522e-518d-4cd0-b16b-0cf2bfdbce70)

In fact, if I remove this from the code and use it to query the same layer.
![image](https://github.com/user-attachments/assets/5fe83ae2-cdec-494a-9369-8fae2bbbb421)

It goes onto the pagination because exceededTranferLimit is true even though the transfer limit wasn't exceeded, and then goes on to return the whole layer for the aforementioned issue. exceededTransferLimit isn't false until there isn't anything left in the table to exceed it with.

**Comment by nanaeaubry** [comment] 2024-09-20 15:11
@JesseRussell411 I have started working on a fix for the issue you are posting about. Do you have some test code to run as well? I have been able to test with a layer from living atlas and saw the issue with `result_record_count` not being respected. 

The fix put in would respect this parameter. However, from all you have posted are there any edge cases you found? If so can you please post reproducible code

**Comment by JesseRussell411** [comment] 2024-09-24 15:44
I would just try a few scenarios to make sure it does what you'd expect:

* result_record_count > transferLimit
* result_record_count = transferLimit
* result_record_count < transferLimit
* result_record_count = 0
* result_record_count = None

And make sure it doesn't skip items.

Also. Do you know if what I found out about exceededTransferLimit in the rest api is a bug or expected behavior (https://github.com/Esri/arcgis-python-api/issues/2027#issuecomment-2350062913)? It doesn't respect resultRecordCount, it seems to be based on how big the full query is, not on how many items are actually requested. Of course, that's an issue with the server's api, not the python package, so this is probably the wrong place to report it. If it is a bug, where should I report it?

**Comment by nanaeaubry** [comment] 2024-09-25 07:29
@JesseRussell411 

Thanks for providing this detail. For `result_record_count` being None we would expect all records to be returned since this parameter is expecting an int. Just letting you know incase you test as well.


As for your comment, it seems to be a bug on the REST API, I will contact the team and let you know if there are any updates

**Comment by nanaeaubry** [comment] 2024-09-27 06:31
@JesseRussell411 Here is some explanation I got:

<html>
<body>
<span data-teams="true"><span class="ui-provider a b c d e f g h i j k l m n o p q r s t u v w x y z ab ac ae af ag ah ai aj ak" dir="ltr"><ul><li>The <code>exceededTransferLimit</code> property:
<ul><li>This is a new property included in JSON responses when you're paging through query results.</li><li>It's used when you're using the <code>resultOffset</code> and <code>resultRecordCount</code> parameters.</li></ul></li><li>What it means:
<ul><li>If <code>exceededTransferLimit</code> is <code>true</code>: There are more results available. You can continue paging.</li><li>If <code>exceededTransferLimit</code> is <code>false</code> or not present (From my test it looks like when false it won't show in JSON): You've reached the end of the results.</li></ul></li><li>When not using paging parameters:
<ul><li>The <code>exceededTransferLimit</code> property might still appear.</li><li>In this case, it will be <code>true</code> only if the number of records is more than what the server administrator has set as the maximum.</li></ul></li><li>Special cases when using paging parameters:
<ul><li>Sometimes, <code>exceededTransferLimit</code> might be <code>true</code> even if you haven't reached the <code>resultRecordCount</code> you specified.</li><li>This happens because of how the system filters results internally.</li><li>The key point: Always use <code>exceededTransferLimit</code> to decide whether to keep paging, not the number of results you get.</li><li>In rare cases, you might get zero results, but <code>exceededTransferLimit</code> is still <code>true</code>. Keep paging in these situations until <code>exceededTransferLimit</code> is no longer returned.<br><br><br>
&nbsp;Another example to help understand the logic:<br><br>
Lets say I have a query that we know it will return <strong>39</strong> features, then if I set query with following params&nbsp;</li></ul></li></ul><p>&nbsp;</p>
Result Offset: | 0
-- | --
Result Record Count: | 20

<p>&nbsp;</p><p>Then I will get <code>"exceededTransferLimit": true</code>, because 39 is exceed 20, so it is true</p><p>Then if I set Result RecordCount as a number greater than 39, say 50, &nbsp;then we query again we will not see <code>exceededTransferLimit </code>in json which means is false</p></span></span>
</body>
</html>

**Comment by nanaeaubry** [comment] 2024-10-01 10:12
@JesseRussell411 
This issue has been addressed and the fix will be released in an upcoming patch (this week or next)

**Closed by nanaeaubry** 2024-10-01 10:12 UTC
Labels: bug
