### ISSUE TITLE
Token required but not passed in the request. 

### ISSUE THREAD

**Issue by redcican** [Esri/arcgis-python-api#1318] opened 2022-08-03 13:30 UTC
I am trying to run this notebook,
[finding_routes_for_appliance_delivery_with_VRP_solve](https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/finding_routes_for_appliance_delivery_with_VRP_solver.ipynb)
 but I kept having this error:
```
Exception: Token required but not passed in the request.
Token required.
(Error Code: 499)
```
when run to the code:
```
# Read the csv file and convert the data to feature set
orders_df = pd.read_csv(orders_csv)
orders_sdf = pd.DataFrame.spatial.from_df(orders_df, "Address")
orders_fset = orders_sdf.spatial.to_featureset()
```
I tried to access Gis by:

```
gis = GIS(url="https://*******.maps.arcgis.com/home/", username="*****", password="******")
```

I don't have a pro account, and I am running my code on Google Colab. Do I need a Pro account to access this service? Or anyone can tell me how to access this service?

**Comment by achapkowski** [comment] 2022-08-03 14:26
No Arcpy is not needed. What version of the API are you using?

**Comment by redcican** [comment] 2022-08-03 14:34
@achapkowski `arcgis-2.0.1`

I followed [arcgic install with minimum](https://developers.arcgis.com/python/guide/install-and-set-up/#Install-with-minimum-dependencies).

What do you mean "No Arcpy is not needed"?

**Comment by achapkowski** [comment] 2022-08-03 14:35
Oops I was looking at two issues at once :)  Thanks, I can not try testing it and seeing what is up.

**Comment by redcican** [comment] 2022-08-03 14:37
@achapkowski 
so what is the most handy way to get access from Gis? If I am not a Pro user.

**Comment by achapkowski** [comment] 2022-08-03 15:21
Provide a username/password into the GIS object.

```python
GIS(username='foo', password='bar') # this connects to AGOL
```

See: https://developers.arcgis.com/python/guide/using-the-gis/ and https://developers.arcgis.com/python/guide/working-with-different-authentication-schemes/

**Comment by redcican** [comment] 2022-08-03 15:27
@achapkowski 
I got the same error: 

Exception                                 Traceback (most recent call last)
[<ipython-input-70-c9f683cdfb2d>](https://localhost:8080/#) in <module>()
----> 1 orders_sdf = pd.DataFrame.spatial.from_df(orders_csv, "Address")
      2 orders_fset = orders_sdf.spatial.to_featureset()

5 frames
[/usr/local/lib/python3.7/dist-packages/arcgis/features/geo/_accessor.py](https://localhost:8080/#) in from_df(df, address_column, geocoder, sr, geometry_column)
   2606                         list(df[address_column]),
   2607                         geocoder=geocoder,
-> 2608                         as_featureset=True,
   2609                     ).sdf.sort_values(by="ResultID")
   2610                     piece_df.index = df.index

[/usr/local/lib/python3.7/dist-packages/arcgis/geocoding/_functions.py](https://localhost:8080/#) in batch_geocode(addresses, source_country, category, out_sr, geocoder, as_featureset, match_out_of_range, location_type, search_extent, lang_code, preferred_label_values, out_fields)
   1634         lang_code,
   1635         preferred_label_values,
-> 1636         out_fields,
   1637     )
   1638 

[/usr/local/lib/python3.7/dist-packages/arcgis/geocoding/_functions.py](https://localhost:8080/#) in _batch_geocode(self, addresses, source_country, category, out_sr, as_featureset, match_out_of_range, location_type, search_extent, lang_code, preferred_label_values, out_fields)
    451             if out_fields is not None:
    452                 params["outFields"] = out_fields
--> 453             resp = self._con.post(url, params)
    454             if resp is not None and as_featureset:
    455                 sr = resp["spatialReference"]

[/usr/local/lib/python3.7/dist-packages/arcgis/gis/_impl/_con/_connection.py](https://localhost:8080/#) in post(self, path, params, files, **kwargs)
   1410             file_name=file_name,
   1411             try_json=try_json,
-> 1412             force_bytes=kwargs.pop("force_bytes", False),
   1413         )
   1414 

[/usr/local/lib/python3.7/dist-packages/arcgis/gis/_impl/_con/_connection.py](https://localhost:8080/#) in _handle_response(self, resp, file_name, out_path, try_json, force_bytes, ignore_error_key)
    898                     return data
    899                 errorcode = data["error"]["code"] if "code" in data["error"] else 0
--> 900                 self._handle_json_error(data["error"], errorcode)
    901             return data
    902         else:

[/usr/local/lib/python3.7/dist-packages/arcgis/gis/_impl/_con/_connection.py](https://localhost:8080/#) in _handle_json_error(self, error, errorcode)
    921 
    922         errormessage = errormessage + "\n(Error Code: " + str(errorcode) + ")"
--> 923         raise Exception(errormessage)
    924 
    925     def post_multipart(

Exception: Token required but not passed in the request.
Token required.
(Error Code: 499)

**Comment by achapkowski** [comment] 2022-10-26 11:40
In 2.1.0, which is released in Early Q1 of 2023, we cannot reproduce the issue, I am making this as fixed in a future release.  Also we cannot reproduce this in 2.0.1, make your credentials are incorrect.

**Closed by achapkowski** 2022-10-26 11:40 UTC
Labels: question
