### ISSUE TITLE
prepare_data from arcgis.learn modules fails to read the data in Azure N series VM

### ISSUE THREAD

**Issue by bharanigurminder** [Esri/arcgis-python-api#589] opened 2020-01-25 11:32 UTC
**Describe the bug**
We had recently acquired azure's N series VM which are powered by the NVIDIA Tesla K80 card and the Intel Xeon E5-2690 v3 (Haswell) processor. We have been working with arcgis.learn module with VM's without GPU and were successfully able to work on unet semantic segmentation using the arcgis.learn.UnetClassifier classifier. 

However, when we shifted to GPU enabled Azure N series VM we started facing issue with arcgis.learn prepare_data.

**To Reproduce**
```python
import arcgis
from arcgis.learn import prepare_data
import fastai
import torch
import torchvision
print(arcgis.__version__)
print(fastai.__version__)
print(torch.__version__)
print(torchvision.__version__)

1.6.2
1.0.39
1.0.0
0.2.2

data = prepare_data(path=r'Path/to/training/data',batch_size=16)
```
error:
```python
Exception                                 Traceback (most recent call last)
<ipython-input-2-b64d83b2729f> in <module>
----> 1 data = prepare_data(path=r'Path/to/training/data',batch_size=16)

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-deeplearningpro\lib\site-packages\arcgis\learn\_data.py in prepare_data(path, class_mapping, chip_size, val_split_pct, batch_size, transforms, collate_fn, seed, dataset_type)
    130 
    131     if not HAS_FASTAI:
--> 132         _raise_fastai_import_error()
    133 
    134     if type(path) is str:

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-deeplearningpro\lib\site-packages\arcgis\learn\_data.py in _raise_fastai_import_error()
     20 
     21 def _raise_fastai_import_error():
---> 22     raise Exception('This module requires fastai, PyTorch and torchvision as its dependencies. Install it using "conda install -c pytorch -c fastai fastai=1.0.39 pytorch=1.0.0 torchvision"')
     23 
     24 def _bb_pad_collate(samples, pad_idx=0):

Exception: This module requires fastai, PyTorch and torchvision as its dependencies. Install it using "conda install -c pytorch -c fastai fastai=1.0.39 pytorch=1.0.0 torchvision"
```
**Screenshots**
![image](https://user-images.githubusercontent.com/16514130/73120560-d5ed5800-3f95-11ea-961a-5d0d3e49a8fb.png)

**Expected behavior**
The data should have been processed, the same data works on Azure VM without GPU component. 

**Platform (please complete the following information):**
 - OS: Windows server 2019
 - VM: Standar_NC6, to know more visit: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-gpu
 - Browser: Google chrome
 - Python API Version: 1.6.2, tested on 1.7.0 issue persists 

**Additional context**
I have tested on ArcGIS Pro's environment as well as tried creating a new environment using Anaconda, the issue still persists on the GPU enabled Azure's N series VM.

**Comment by achapkowski** [comment] 2020-01-27 11:49
@priyankatuteja can you please take a look at this?

**Comment by bharanigurminder** [comment] 2020-02-17 09:02
Since torchvision is a high level neural network API it uses Pillow to stack the data required for training. On Windows pillow has issues opening image files. On further researching, I found many bugs related to Pillow library having issues with tiff file and recommendations suggested to downgrade the libtiff library to make it work. Even after downgrading the libtiff module the issues still persist. After multiple failed attempts I finally exported the training data into jpeg format. This a workaround worked for me.

**Comment by priyankatuteja** [comment] 2020-04-13 04:21
One way we can try to find out the issue with your environment is:
1. Open your ArcGIS folder and ''C:\Users\username\anaconda3\envs\arc162\Lib\site-packages\arcgis\learn\_data.py''. This is roughly the path where you will find this file. Here you see the code as provided in screenshot below

![image](https://user-images.githubusercontent.com/39754605/79091463-f7770800-7d6a-11ea-8bf9-f23d821cc5f2.png)
You can remove the "try and except" from the code and save it, restart the notebook and this time you should get a better message about what exactly is breaking. 

![image](https://user-images.githubusercontent.com/39754605/79091509-2e4d1e00-7d6b-11ea-8d1a-386162b8b0ef.png)

Let us know if you could try this, it will give us a better hint.

**Comment by priyankatuteja** [comment] 2020-04-13 04:21
One way we can try to find out the issue with your environment is:
1. Open your ArcGIS folder and ''C:\Users\username\anaconda3\envs\arc162\Lib\site-packages\arcgis\learn\_data.py''. This is roughly the path where you will find this file. Here you see the code as provided in screenshot below

![image](https://user-images.githubusercontent.com/39754605/79091463-f7770800-7d6a-11ea-8bf9-f23d821cc5f2.png)
You can remove the "try and except" from the code and save it, restart the notebook and this time you should get a better message about what exactly is breaking. 

![image](https://user-images.githubusercontent.com/39754605/79091509-2e4d1e00-7d6b-11ea-8d1a-386162b8b0ef.png)

Let us know if you could try this, it will give us a better hint.

**Comment by cdflint** [comment] 2020-04-24 15:36
Similar issue to the OP. 

![image](https://user-images.githubusercontent.com/25038329/80229222-1b193880-861e-11ea-8806-7ea1f18e2722.png)

error:

![image](https://user-images.githubusercontent.com/25038329/80229261-2c624500-861e-11ea-91eb-29e26513c1e7.png)

Trace back to imports from arcgis.learn._data seem to show that there is a broken dependency to a function in fastprogress for the 'progress_bar'

![image](https://user-images.githubusercontent.com/25038329/80230284-bf4faf00-861f-11ea-83e1-48a713da0c81.png)

It appears to be imported as:

from fastprogress import progress_bar

per fastprogress it should be:

from fastprogress.fastprogress import progress_bar

![image](https://user-images.githubusercontent.com/25038329/80230362-d7273300-861f-11ea-9557-6284744ac238.png)

Hope this helps.

**Comment by priyankatuteja** [comment] 2020-04-26 06:36
@cdflint The fast progress version seems to be incompatible. 

Please try the following command
```
conda install -c esri arcgis fastai pillow scikit-image --no-pin

```

This will update the ArcGIS version to 1.8.0 FYI

**Comment by cdflint** [comment] 2020-04-26 12:41
When running that command I got an update for arcgis 1.7.0 to 1.7.1. Also note the conda install command thrown in the original error statement.  It specifically says to install fastai v1.0.54.  

Fixing the fasprogress import statements in:

arcgis.learn.models._maskrcnn_utils
arcgis.learn.models._ssd_utils

From:
from fastprogress important progress_bar
To:
from fastprogress.fastprogress import progress_bar

Resolves the import error from the original issue.  

Additionally, but not related to this issue; the torchvision version that is installed based on related dependencies relies on an older version of pillow using --no-pin installs pillow 7.0.0. Where the last non-breaking version is 6.2.2.

For the benefit of others a conda yaml with the working version dependencies when an arcgis API is released could aleviate some of these issues.  I know everyone's development environment is going to be different at some level (os, graphics drivers, cpu, etc.), but conda does a really good job on stitching these dependencies together. Or better yet burn those hard dependencies into the requirements of the arcgis API.  If you have modules like learn that require strict versions of in managed python modules it makes perfect sense to me to require them at the install of the API for full functionality.

**Comment by priyankatuteja** [comment] 2020-04-26 15:18
@cdflint What version of Pro are you using?

**Comment by cdflint** [comment] 2020-04-26 15:22
Pro 2.5.0

Using a cloned environment of arcgispro-py3 to install external python modules.

**Comment by priyankatuteja** [comment] 2020-04-26 16:53
@cdflint I am trying to reproduce the same error at my end, meanwhile could you do the follwoing:
Open python command prompt and run command "proswap arcgispro-py3" if default is not set to the original environment. Then create a fresh clone using "conda create --name DeepLearningEnv --clone arcgispro-py3". To install all required dependencies for arcgis.learn module, run "conda install -c esri arcgis fastai pillow scikit-image --no-pin". Let me know if you still get similar issues

**Comment by cdflint** [comment] 2020-04-27 14:42
On a clean conda env this does resolve the issues mentioned above, the cause for the 'out of sync package versions' was that they were not being pulled from the esri channel directly, but from the one of various others (fastai, anaconda, etc.).  Like mentioned above the pillow and fastprogress versions in the esri repo are 6.2.2 and 0.1.21 respectfully. 

As soon as someone needs a package that isn't in the esri channel they will need to add another (anaconda, conda-forge, pkgs/main etc.).  The potential of pulling out of sync repos will arise again.

**Comment by priyankatuteja** [comment] 2020-04-27 15:04
@cdflint  We have provided compatible versions of the packages in the Esri channel to address these issues. Glad to know the issue is resolved with the clean cloned env and using the Esri channel.

**Closed by priyankatuteja** 2020-04-27 15:04 UTC
Labels: bug

**Comment by cdflint** [comment] 2020-04-27 15:30
To reproduce use the install command in the Exceptions raised by arcgis.learn.prepare_data by either of the error statements posted by myself or OP.

original Exception: 
```python
"""Exception: This module requires fastai, PyTorch and torchvision as its dependencies. Install it using 'conda install -c pytorch -c fastai fastai=1.0.39 pytorch=1.0.0 torchvision'"""
```

my Exception:
```python
"""Exception: This module requires fastai, PyTorch and torchvision and its dependencies.
Install them using 'conda install -c pytorch -c fastai fastai=1.0.54 pytorch=1.0.0 torchvision scikit-image'"""
```

Suggest changing installation_steps for 'win32' to match ['linux','darwin'] in _data.py to reflect the working code so future errors thrown won't lead down the same path.

### ref arcgis.learn._data.py (v1.8.0)[line 81]
![image](https://user-images.githubusercontent.com/25038329/80390177-181a8400-887a-11ea-8ea5-190f0bc37705.png)
