### ISSUE TITLE
using pivot with SHAPE as index or in columns results in an Error with version 2.1.0

### ISSUE THREAD

**Issue by BoudewijnBoogaard** [Esri/arcgis-python-api#1459] opened 2023-02-08 00:14 UTC
**Describe the bug**
For some data wrangling I'm using pivot on a panda's data frame that is spatially enabled using the Shape column as an index. In version 2.0.1 that ships with ArcGIS Pro 3.0 this works fine. On version 2.1.0 that ships with ArcGIS Pro 3.1 beta I'm getting an error.

It also fails if the SHAPE column is in the columns parameter.

**To Reproduce**
Load data into a spatially enabled data frame
Use pivot on the data frame with SHAPE as the index or the column

error:
```python
Traceback (most recent call last):
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\arrays\categorical.py", line 438, in __init__
    codes, categories = factorize(values, sort=True)
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\algorithms.py", line 749, in factorize
    codes, uniques = values.factorize(na_sentinel=na_sentinel)
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\arrays\base.py", line 1028, in factorize
    uniques_ea = self._from_factorized(uniques, self)
TypeError: _from_factorized() takes 2 positional arguments but 3 were given
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-20f2b05f847c>", line 1, in <cell line: 1>
    tst = df_interpolate.pivot(index=['SHAPE', 'city', 'time_stamp'], columns=['variable'], values=['value'])
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\frame.py", line 7885, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\reshape\pivot.py", line 510, in pivot
    multiindex = MultiIndex.from_arrays(index_list)
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\indexes\multi.py", line 489, in from_arrays
    codes, levels = factorize_from_iterables(arrays)
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\arrays\categorical.py", line 2881, in factorize_from_iterables
    codes, categories = zip(*(factorize_from_iterable(it) for it in iterables))
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\arrays\categorical.py", line 2881, in <genexpr>
    codes, categories = zip(*(factorize_from_iterable(it) for it in iterables))
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\arrays\categorical.py", line 2854, in factorize_from_iterable
    cat = Categorical(values, ordered=False)
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\arrays\categorical.py", line 440, in __init__
    codes, categories = factorize(values, sort=False)
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\algorithms.py", line 749, in factorize
    codes, uniques = values.factorize(na_sentinel=na_sentinel)
  File "C:\Users\bbo\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\pandas\core\arrays\base.py", line 1028, in factorize
    uniques_ea = self._from_factorized(uniques, self)
TypeError: _from_factorized() takes 2 positional arguments but 3 were given
```

**Platform (please complete the following information):**
 - OS: Windows 11
 - Python API Version 2.1.0

**Comment by achapkowski** [comment] 2023-02-08 23:28
Can you post a reproducible sample?

**Comment by nanaeaubry** [comment] 2023-02-22 21:51
@BoudewijnBoogaard Can you post a reproducible sample for us? Thanks

**Comment by achapkowski** [comment] 2023-04-21 17:04
Closing because no sample code provided.  We'll reopen if you provide a reproducible sample.

**Closed by achapkowski** 2023-04-21 17:04 UTC
Labels: bug
