### ISSUE TITLE
spatial.to_featureset() returns date fields as float when the first row is NaT

### ISSUE THREAD

**Issue by justingreco** [Esri/arcgis-python-api#1864] opened 2024-07-09 21:22 UTC
**Describe the bug**
When the first row in the dataframe has a null date, spatial.to_featureset() returns the dates as float instead of int.  This results in edit_features failing with the following error, since the dates are floats.  

**To Reproduce**
```python
from arcgis.gis import GIS
gis = GIS()
item = gis.content.get('5c52412b69204b7db4fa399f13d9dc18')
layer = item.layers[0]
df = layer.query().sdf
fs = df.spatial.to_featureset()
layer.edit_features(adds=fs)
```
error:
```python
The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 5 ("@datefield"): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.
```
**Screenshots**

**Expected behavior**
spatial.to_featureset() should return date columns as integers instead of float

**Platform (please complete the following information):**
 - OS: macOS, though I am running this a a notebook on ArcGIS Online
 - Browser Chrome
 - Python API Version 2.3.0 and 2.3.0.3

**Additional context**
I verified that this does not occur at version 2.2.0

**Comment by nanaeaubry** [comment] 2024-07-15 13:09
Thanks for reporting! This was addressed and duplicate of https://github.com/Esri/arcgis-python-api/issues/1819
The fix is in the next release

**Closed by nanaeaubry** 2024-07-15 13:09 UTC
Labels: bug
