### ISSUE TITLE
target_item owner is assigned to source_item.owner. This throws an exception as source_item.owner does not exist in target portal

### ISSUE THREAD

**Issue by ujjwaln** [Esri/arcgis-python-api#483] opened 2019-08-05 04:19 UTC
https://github.com/Esri/arcgis-python-api/blob/69d5a4c42b2dc598bc9d2ad14e37ec67ecd8ffb1/samples/03_org_administrators/AdminClonePortal/clone_portal.py#L273

**Comment by achapkowski** [comment] 2022-05-23 10:25
closing because there is no reproducible sample.

**Closed by achapkowski** 2022-05-23 10:25 UTC
