### ISSUE TITLE
Inconsistent Number of Items From content.search + Group.content

### ISSUE THREAD

**Issue by BrettFrahm** [Esri/arcgis-python-api#1648] opened 2023-09-01 14:45 UTC
**Describe the bug**
I'm getting an inconsistent number of items from the content.search() and Group.content(). I have print statement outputs from 6 subsequent tests below in the error section that ran on the same code that all provided different results. Each run has it printing the number of items with len() in content.search(), Group.content(), and there is also a section trying to find a particular item in a group.

**To Reproduce**
```python
import arcgis.gis as api
ago = api.GIS("https://trpd.maps.arcgis.com", "ABCD", "####")

ago_item_search = ago.content.search(query="", sort_field='type', sort_order='asc', max_items=10000)
print(len(ago_item_search))

gallery = api.Group(ago, '492480f8e7dd4780b5d28a4a5aa01cf8')
print(len(gallery.content(max_items=10000)))

gallery_ids = []
for content in gallery.content(max_items=10000):
    gallery_ids.append(content['id'])

if 'd133c91d0c1149d4a5a3dbed7978476f' in gallery_ids:
    print('IN')
else:
    print('NOT IN')
```
error:
```python
7240
3700
IN

7140
900
NOT IN

7240
200
IN

7240
1100
NOT IN

7240
900
IN

7440
6856
NOT IN

```

**Expected behavior**
The results of these search functions should be consistent every time if the number of items has not changed in arcgis online.

**Platform (please complete the following information):**
 - OS: Windows
 - Python API Version: 2.0.1

**Comment by nanaeaubry** [comment] 2023-09-06 06:07
@BrettFrahm  Hello, 2.0.1 is an older version, could you upgrade to the latest (2.1.0.3) and try again?

**Comment by BrettFrahm** [comment] 2023-09-06 20:10
@nanaeaubry

I was able to test again with 2.0.1 as well as 2.1.0.2 (I'm on Pro 3.1.2) and both tests had consistent results. Perhaps there was some kind of service disruption for the API on September 1st? I can try again tomorrow and see if it is any different.

**Comment by nanaeaubry** [comment] 2023-09-07 07:18
@BrettFrahm  Thanks for testing, we will take a look and I'll post any updates here from our end

**Comment by BrettFrahm** [comment] 2023-09-13 18:32
@nanaeaubry just letting you know that I have not been able to reproduce the issue since the 1st of September.

**Comment by achapkowski** [comment] 2023-09-13 19:24
Ok, since you can reproduce it, let's close this and chalk it up to server gremlins.  

If it happens again, please let us know.

Thank you

**Closed by achapkowski** 2023-09-13 19:24 UTC
Labels: bug
